spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:54321}/${DB_NAME:handy-service}
    username: ${DB_USER:handyy}
    password: ${DB_PWD:handyy}
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: true